#!/bin/zsh

#              o8o                                            .o8            
#              `"'                                           "888            
# oooo    ooo oooo          ooo. .oo.  .oo.    .ooooo.   .oooo888   .ooooo.  
#  `88.  .8'  `888          `888P"Y88bP"Y88b  d88' `88b d88' `888  d88' `88b 
#   `88..8'    888  8888888  888   888   888  888   888 888   888  888ooo888 
#    `888'     888           888   888   888  888   888 888   888  888    .o 
#     `8'     o888o         o888o o888o o888o `Y8bod8P' `Y8bod88P" `Y8bod8P' 

    export KEYTIMEOUT=1

    autoload edit-command-line; zle -N edit-command-line
    bindkey '^v' edit-command-line

    zmodload -i zsh/complist

    # Use vim keys in tab complete menu:
    bindkey -M menuselect 'h' vi-backward-char
    bindkey -M menuselect 'k' vi-up-line-or-history
    bindkey -M menuselect 'l' vi-forward-char
    bindkey -M menuselect 'j' vi-down-line-or-history
    # bindkey -v '^?' backward-delete-char

    # Change cursor shape for different vi modes.
    function zle-keymap-select () {
        case $KEYMAP in
            vicmd) echo -ne '\e[1 q';;      # block
            viins|main) echo -ne '\e[5 q';; # beam
        esac
    }
    zle -N zle-keymap-select
    zle-line-init() {
        zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
        echo -ne "\e[5 q"
    }
    zle -N zle-line-init
    echo -ne '\e[5 q' # Use beam shape cursor on startup.
    preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.
